# Generated by Django 5.0.2 on 2024-02-06 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['created']},
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='initial_bid',
            new_name='initial_price',
        ),
        migrations.RemoveField(
            model_name='auctionphoto',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='active',
        ),
        migrations.AddField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 0, 40, 8, 204111)),
        ),
        migrations.AddField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 0, 40, 8, 204111)),
        ),
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 7, 0, 40, 38, 290282)),
            preserve_default=False,
        ),
    ]
