# Generated by Django 5.0.2 on 2024-02-07 17:49

import datetime

import django.utils.timezone
from django.db import migrations, models

import auction.models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0002_auctionphoto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={"ordering": ["created"]},
        ),
        migrations.RemoveField(
            model_name="auction",
            name="initial_bid",
        ),
        migrations.RemoveField(
            model_name="auctionphoto",
            name="author",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="active",
        ),
        migrations.AddField(
            model_name="auction",
            name="end_time",
            field=models.DateTimeField(default=auction.models.get_auto_end_time),
        ),
        migrations.AddField(
            model_name="auction",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="initial_price",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auction",
            name="min_bid_price_gap",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auction",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="auction",
            name="started",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bid",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 7, 19, 49, 36, 101633)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bid",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
