# Generated by Django 5.0.2 on 2024-02-07 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_bid_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='min_bid_price_gap',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 14, 47, 28, 325819)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='initial_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 14, 47, 28, 325819)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
