# Generated by Django 5.0.2 on 2024-02-07 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_auction_min_bid_price_gap_alter_auction_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 17, 42, 48, 854121)),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 7, 17, 42, 48, 854121)),
        ),
    ]
