# Generated by Django 5.0.2 on 2024-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0004_alter_auction_end_time_alter_auction_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="won",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="auction",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
