# Generated by Django 5.0.2 on 2024-02-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_bid_won_alter_auction_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="bid",
            name="leader",
            field=models.BooleanField(default=True),
        ),
    ]
